# Generated by Django 4.0.1 on 2022-07-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings50', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('overview', models.CharField(max_length=512)),
                ('release_date', models.DateField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, default=None, upload_to='posters')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('director', models.CharField(blank=True, default=None, max_length=32)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('certification', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ratings50.certification')),
                ('genre', models.ManyToManyField(blank=True, related_name='movie', to='ratings50.Genre')),
            ],
        ),
    ]
