# Generated by Django 4.0.1 on 2022-07-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings50', '0005_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'user')},
        ),
    ]
