# Generated by Django 4.0.1 on 2022-07-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings50', '0008_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='ratings50.review'),
        ),
    ]
