# Generated by Django 4.0.1 on 2022-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings50', '0009_alter_vote_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
