# Generated by Django 4.0.1 on 2022-07-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings50', '0011_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ratings50.review'),
        ),
    ]
